# Generated by Django 2.2.6 on 2019-11-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
