# Generated by Django 2.2.6 on 2019-11-03 19:17

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Dokumnet sprawdzianu', 'verbose_name_plural': 'Dokumenty sprawdzianów'},
        ),
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.upload_to, verbose_name='Obraz'),
        ),
    ]
